// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_T34uVms6Q_HQEkPTa8paKIhUh1k2pE',
    appId: '1:969308717730:web:006934efbff1ee17790dfb',
    messagingSenderId: '969308717730',
    projectId: 'last-fd99b',
    authDomain: 'last-fd99b.firebaseapp.com',
    storageBucket: 'last-fd99b.appspot.com',
    measurementId: 'G-33H0TGF6F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqAj6e6B0IJ0z6uBCCF4k17LM681xckg',
    appId: '1:969308717730:android:8f4b1c35a1d4e6d1790dfb',
    messagingSenderId: '969308717730',
    projectId: 'last-fd99b',
    storageBucket: 'last-fd99b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNe2YcqgKkO1roLrNdZAcpMI8SkbI59hM',
    appId: '1:969308717730:ios:ba8245f36ce1eedb790dfb',
    messagingSenderId: '969308717730',
    projectId: 'last-fd99b',
    storageBucket: 'last-fd99b.appspot.com',
    iosBundleId: 'com.example.last',
  );
}
